#include "../Podd/FadcStandaloneAnalyzer.h"
#include "RtypesCore.h"
#include "waveformGenerator.h"
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <iostream>

// ─── Helpers ─────────────────────────────────────────────────────────────────

// waveformGenerator returns Int_t samples; FADCStandaloneAnalyzer::Analyze()
// takes Double_t. This helper does the element-wise cast.
std::vector<Double_t> ToDoubleWave(const std::vector<Int_t> &wave) {
  return std::vector<Double_t>(wave.begin(), wave.end());
}

// Shared analyzer configuration.
FADCConfig GetTestConfig() {
  FADCConfig conf;
  conf.fNPedestalSamples = 4;
  conf.fSampThreshold = 25.0;
  conf.fNSB = 1;
  conf.fNSA = 4;
  conf.fNSAT = 1;
  conf.fMaxNPulses = 3;
  return conf;
}

// ─── Tests ───────────────────────────────────────────────────────────────────
// Waveform generator v2 tests
TEST_CASE(
    "WaveformAnalyzer correctly processes waveforms generated by generator v2",
    "[analyzer]") {
  FadcStandaloneAnalyzer analyzer;
  analyzer.setConfig(GetTestConfig());
  FADCCalib calib = {0.2441, 4.0 / 50.0};
  analyzer.setCalib(calib);

  const FADCConfig &conf = analyzer.getConfig();

  // Keeping default values
  WaveformParams wfParams;
  DigitizerParams daqParams;

  waveformGenerator gen;
  gen.setDetectorParams(wfParams);
  gen.setDigitizerParams(daqParams);

  SECTION("Empty waveform returns no pulses and doesn't crash") {
    std::vector<Double_t> empty_wave;
    auto results = analyzer.Analyze(empty_wave, 1.0, 4.0);
    REQUIRE(results.fNSampPulses == 0);
  }

  SECTION("Noise waveform (below threshold) returns no pulses") {
    // Generate a pure noise waveform and confirm the analyzer finds nothing.
    std::vector<Double_t> wave = ToDoubleWave(gen.noiseWaveform());
    auto results = analyzer.Analyze(wave, 1.0, 4.0);
    REQUIRE(results.fNSampPulses == 0);
  }

  SECTION("Generate exponential waveform") {
    std::vector<Int_t> int_wave = gen.generateWaveform();
    std::vector<Double_t> wave = ToDoubleWave(int_wave);

    // --- FADCStandaloneAnalyzer result ---
    auto results = analyzer.Analyze(wave, 1.0, 4.0);

    // Output shouldn't be empty
    REQUIRE(results.fNSampPulses >= 1);
    // Pulse parameters using waveformGenerator class (for comparison)
    // gen.clearTruthInfo();
    const TruthPulseInfo &wfInfo = gen.getTruthInfo();

    Double_t int_margin = (daqParams.noise_sigma) * (conf.fNSA + conf.fNSB) *
                          daqParams.sample_rate;
    Double_t amp_margin = daqParams.noise_sigma * 2;
    Double_t time_margin = 64.0 * (wfParams.tts_sigma / daqParams.sample_rate);

    std::cout << "\nCalculated Integrals and times for Multiple Pulses:\n";
    for (int i = 0; i < (int)wfInfo.pulseIntegral.size(); i++) {
      std::cout << "\tPulse Number: " << i + 1 << std::endl;
      std::cout << "\tPulse Integral: From Waveform generator: "
                << wfInfo.pulseIntegral[i] << " from FADCStandaloneAnalyzer "
                << results.fSampPulseIntPedSub[i] << std::endl;
      REQUIRE(results.fSampPulseIntPedSub[i] ==
              Catch::Approx(static_cast<Double_t>(wfInfo.pulseIntegral[i]))
                  .margin(int_margin));
      REQUIRE(results.fSampPulseAmp[i] ==
              Catch::Approx(static_cast<Double_t>(wfInfo.pulseAmplitude[i]))
                  .margin(amp_margin));

      std::cout << "\tPulse Time: From Waveform generator "
                << wfInfo.pulseTime[i] << " from FADCStandaloneAnalyzer "
                << results.fSampPulseTime[i] << "\n\n";
      REQUIRE(results.fSampPulseTime[i] ==
              Catch::Approx(static_cast<Double_t>(wfInfo.pulseTime[i]))
                  .margin(time_margin));
    }
  }
}