## -*- mode: Python -*-

import os
import sys
import SCons.Util

analyzer_dir = '..'

sys.path.append(analyzer_dir + '/site_scons')
import configure

env = Environment(ENV = os.environ)

configure.FindROOT(env, need_glibs = False)
configure.FindEVIO(env, build_it = False)

flags = { 'LIBS'    : Split('HallA dc evio'),
          'LIBPATH' : [analyzer_dir,env.subst('$EVIO_LIB')],
          'CPPPATH' : Split('-I'+analyzer_dir+'/src -I'+analyzer_dir+'/hana_decode') }
env.MergeFlags(flags)

# Configure
if not (env.GetOption('clean') or env.GetOption('help')):
        # Initial configuration using our custom configure.py module
        configure.config(env,ARGUMENTS)

        conf = Configure(env)
        if not conf.CheckCXX():
                print('!!! Your compiler and/or environment is not correctly configured.')
                Exit(1)
        env = conf.Finish()

Export('env')

# Build targets
env.Program('dbconvert', 'dbconvert.cxx')
